default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myapp
  password:

development:
  <<: *default
  database: dew_set_dev

test:
  <<: *default
  database: dew_set_test

production:
  <<: *default
  database: dew_set_pro
